### PR TITLE
Aggregation options for virtual groups

### PR DESCRIPTION
**Pull request by TyrionWarMage**
This PR adds aggregation modes to virtual groups. (not available in easy mode). Available are:
- uncertain (old behaviour)
- min
- max
- avg
- any (bool any)
- all (bool all)

As i am not skilled in JS, there may be suboptimal code. Please let me know any change requests.

### CODE REVIEW

**Comment by Apollon77** [comment]
LGTM (for the main code) ... can not ay anything for the react part :-)

@TyrionWarMage can you pelase rebase your PR on master? There are conflicts now with updated translation files

**Comment by TyrionWarMage** [comment]
> @TyrionWarMage can you pelase rebase your PR on master? There are conflicts now with updated translation files

Done

**Comment by TyrionWarMage** [comment]
Can this be merged or is something missing?

**Comment by GermanBluefox** [comment]
> Can this be merged or is something missing?

Sorry for delay. Time is missing

**Comment by Apollon77** [comment]
@GermanBluefox short reminder :-)

**Comment by GermanBluefox** [comment]
Thank you

**Pull request merged**
